apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-helm-external
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/robinlioret/poc-iac-gitops-terraform.git
        revision: HEAD
        files:
          - path: workload/**/helm-external.json
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      namespace: argocd
    spec:
      destination:
        namespace: "{{ .dNamespace }}"
        server: https://kubernetes.default.svc
      project: default
      sources:
        - repoURL: "{{ .dRepoURL }}"
          targetRevision: "{{ .dTargetRevision }}"
          chart: "{{ .dChartName }}"
          helm:
            valueFiles:
              - $values/{{ .path.path }}/values.yaml
        - repoURL: https://github.com/robinlioret/poc-iac-gitops-terraform.git
          targetRevision: master
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Prune=true