apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: sample-workspace
spec:
  name: argocd-workspace
  organization: rli-personal
  token:
    secretKeyRef:
      name: terraform-organization-token
      key: token
  applyMethod: auto
  allowDestroyPlan: auto
  description: "ArgoCD generated workspace"
  executionMode: remote
  deletionPolicy: destroy
  project:
    name: poc-gitops-terraform
