apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: kubernetes-operator-demo
  annotations:
    workspace.app.terraform.io/run-type: "apply"

spec:
  name: kubernetes-operator-demo
  organization: rli-personal
  project:
    name: poc-gitops-terraform

  deletionPolicy: destroy
  applyMethod: auto
  executionMode: remote
  token:
    secretKeyRef:
      name: terraform-operator-token
      key: token

  workingDirectory: terraform/sample-s3-bucket
  versionControl:
    oAuthTokenID: <redacted>
    repository: robinlioret/poc-iac-gitops-terraform

  terraformVariables:
    - name: aws_region
      hcl: false
      sensitive: false
      value: eu-west-3

    - name: bucket_name
      hcl: false
      sensitive: false
      value: yolo-from-kubernetes-manifest-through-argocd

    - name: aws_access_key_id
      hcl: false
      sensitive: true
      valueFrom:
        secretKeyRef:
          name: aws-terraform
          key: aki

    - name: aws_secret_access_key
      hcl: false
      sensitive: true
      valueFrom:
        secretKeyRef:
          name: aws-terraform
          key: sak
