apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: kubernetes-operator-demo
spec:
  organization: rli-personal
  token:
    secretKeyRef:
      name: terraform-operator-token
      key: token
  name: kubernetes-operator-demo
  deletionPolicy: destroy